
name: Run Python script

on:
  # schedule:
  #   - cron: '*/30 * * * *' 

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: sportsnews
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Prepare Selenium
        uses: nanasess/setup-chromedriver@master
      - name: Start XVFB
        run: |
         sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
    
      - name: execute py script # run main.py
        env:
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
        run: python main.py
